version: '3.8'

services:
  # FastAPI приложение
  app:
    build: .
    container_name: subscription-flow-app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/subscriptions_db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=true
    depends_on:
      - postgres
      - redis
    networks:
      - subscription-network
    volumes:
      - ./app:/app/app:ro
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro

  # База данных PostgreSQL
  postgres:
    image: postgres:15
    container_name: subscription-flow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: subscriptions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - subscription-network
    ports:
      - "5432:5432"

  # Redis для кэширования
  redis:
    image: redis:7-alpine
    container_name: subscription-flow-redis
    restart: unless-stopped
    networks:
      - subscription-network
    ports:
      - "6379:6379"

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: subscription-flow-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - subscription-network

volumes:
  postgres_data:

networks:
  subscription-network:
    driver: bridge 